
package pe.gob.reniec.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimpleConsultaDniService", targetNamespace = "http://endpoint.wsconsultadni.reniec.gob.pe/", wsdlLocation = "https://srel.reniec.gob.pe/consultadnie/ConsultaDniService?WSDL")
public class SimpleConsultaDniService
    extends Service
{

    private final static URL SIMPLECONSULTADNISERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLECONSULTADNISERVICE_EXCEPTION;
    private final static QName SIMPLECONSULTADNISERVICE_QNAME = new QName("http://endpoint.wsconsultadni.reniec.gob.pe/", "SimpleConsultaDniService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://srel.reniec.gob.pe/consultadnie/ConsultaDniService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLECONSULTADNISERVICE_WSDL_LOCATION = url;
        SIMPLECONSULTADNISERVICE_EXCEPTION = e;
    }

    public SimpleConsultaDniService() {
        super(__getWsdlLocation(), SIMPLECONSULTADNISERVICE_QNAME);
    }

    public SimpleConsultaDniService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLECONSULTADNISERVICE_QNAME, features);
    }

    public SimpleConsultaDniService(URL wsdlLocation) {
        super(wsdlLocation, SIMPLECONSULTADNISERVICE_QNAME);
    }

    public SimpleConsultaDniService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLECONSULTADNISERVICE_QNAME, features);
    }

    public SimpleConsultaDniService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleConsultaDniService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SRELServiceService
     */
    @WebEndpoint(name = "SRELServiceServicePort")
    public SRELServiceService getSRELServiceServicePort() {
        return super.getPort(new QName("http://endpoint.wsconsultadni.reniec.gob.pe/", "SRELServiceServicePort"), SRELServiceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SRELServiceService
     */
    @WebEndpoint(name = "SRELServiceServicePort")
    public SRELServiceService getSRELServiceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.wsconsultadni.reniec.gob.pe/", "SRELServiceServicePort"), SRELServiceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLECONSULTADNISERVICE_EXCEPTION!= null) {
            throw SIMPLECONSULTADNISERVICE_EXCEPTION;
        }
        return SIMPLECONSULTADNISERVICE_WSDL_LOCATION;
    }

}
