package pe.gob.reniec.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "SRELServiceService", targetNamespace = "http://endpoint.wsconsultadni.reniec.gob.pe/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({ObjectFactory.class})
public interface SRELServiceService {


    /**
     * @param arg0
     * @return returns pe.gob.reniec.ws.client.ResultadoConsulta
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.wsconsultadni.reniec.gob.pe/SRELServiceService/consultarRequest", output = "http://endpoint.wsconsultadni.reniec.gob.pe/SRELServiceService/consultarResponse")
    public ResultadoConsulta consultar(@WebParam(name = "arg0", partName = "arg0") PeticionConsulta arg0);

    /**
     * @param arg0
     * @return returns pe.gob.reniec.ws.client.ResultadoConsulta
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.wsconsultadni.reniec.gob.pe/SRELServiceService/consultarCertificadoRequest", output = "http://endpoint.wsconsultadni.reniec.gob.pe/SRELServiceService/consultarCertificadoResponse")
    public ResultadoConsulta consultarCertificado(@WebParam(name = "arg0", partName = "arg0") PeticionConsultaCertificado arg0);

    /**
     * @param arg0
     * @return returns pe.gob.reniec.ws.client.ResultadoActualizacionCredencial
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.wsconsultadni.reniec.gob.pe/SRELServiceService/actualizarCredencialRequest", output = "http://endpoint.wsconsultadni.reniec.gob.pe/SRELServiceService/actualizarCredencialResponse")
    public ResultadoActualizacionCredencial actualizarCredencial(@WebParam(name = "arg0", partName = "arg0") PeticionActualizarCredencial arg0);

}
